### PR TITLE
Security: do not install private keys into rootfs

### PR DESCRIPTION
**Pull request by lumag**
Currently `packagegroup-ima` would pull **private keys** into rootfs. Fix this behaviour and stop one to ever pulling private keys into rootfs by dropping `key-store-*-privkey` packages. There is no reason to have them at all.

### CODE REVIEW

**Comment by jiazhang0** [comment]
@lumag Only the sample keys should be installed. Do you find current implementation breaks this principle?

**Comment by lumag** [comment]
> @lumag Only the sample keys should be installed. Do you find current implementation breaks this principle?

Yes. Current code results in `user` private keys being installed to target rootfs. This means that all target devices with `packagegroup-ima` package will contain both IMA key (encrypted by default) and system trusted key (unencrypted and unprotected), which is a grave security hole.

**Comment by jiazhang0** [comment]
> > @lumag Only the sample keys should be installed. Do you find current implementation breaks this principle?
> 
> Yes. Current code results in `user` private keys being installed to target rootfs. This means that all target devices with `packagegroup-ima` package will contain both IMA key (encrypted by default) and system trusted key (unencrypted and unprotected), which is a grave security hole.

So the problem is that the user private key should not be installed, and the related users private key packages should not be contained in packagegroup-ima. Is there a way to only install the sample private keys?

**Comment by lumag** [comment]
From the security point of view I'd prefer that neither user nor sample
keys have to possibility of getting installed into rootfs.

**Comment by trini** [comment]
Similar to the flag to zap the root password, there can be times where you want the private keys installed.  It should not however be default.

**Comment by jiazhang0** [comment]
@lumag @trini Shall we get rid of the behavior of installing user private keys at the first step?

**Comment by jiazhang0** [comment]
@lumag Could you update this PR with doc update?

**Comment by lumag** [comment]
@jiazhang0 which kind of doc update would you like to receive? I found no doc regarding private key packages.

**Comment by jiazhang0** [comment]
> @jiazhang0 which kind of doc update would you like to receive? I found no doc regarding private key packages.

The 113 line at meta-integrity/README.md. Thanks.

**Comment by lumag** [comment]
@jiazhang0 done

**Comment by jiazhang0** [comment]
> @jiazhang0 done

Thanks. Merged.

**Pull request merged**
