### PR TITLE
Fixes for *_BASE_NAME and *_SYMLINK_NAME variables

### PR DESCRIPTION
**Pull request by yizhao1**

### CODE REVIEW

**Comment by trini** [comment]
I'm concerned that in matching what master has we've now broken support for sumo/rocko, which we have listed as compatible layers.  We may need to add some logic in for compatible names here.

**Comment by twoerner** [comment]
I wonder how long it's going to take Richard to realize the current implementation of compatible layers is broken (for exactly these scenarios)? Sometimes master moves ahead of the latest release in incompatible ways, and there's no way to indicate this.

**Comment by trini** [comment]
@twoerner well, it's on us for declaring that our master supports rocko/sumo/master.  I'm not sure if this set of changes is drastic enough to make that impossible.  But if @jiazhang0 is agreeable I'd also be happy to see about forking rocko/sumo out and handle cherry-picking things from master into rocko as I've been the person needing that the most.

**Comment by yizhao1** [comment]
@jiazhang0 @twoerner @trini Why we don't branch for each release like other meta layers does ? It's very difficult to keep compatibility for 3 releases in one branch. We can branch for sumo/rocko and cherry-pick necessary patches from master. It is easy to do.

**Comment by jiazhang0** [comment]
@trini @twoerner @yizhao1 I'm open on forking branches for long term support. Some ideas are given here to discuss.

1. Create new branch from the coming
   I will do it as early as possible, rather than as we are now.

2. Branch maintainer
    If you would like to take this job, please let me know.
    
3. Define LTS branch scope
    Currently, sumo and rocko are candidates. Actually the key choice is whether we will decide to support rocko.

**Comment by twoerner** [comment]
Ideally we'd support whatever branches are actively maintained by The Yocto Project. This currently means: master, thud, sumo, and rocko: https://wiki.yoctoproject.org/wiki/Stable_branch_maintenance

**Comment by trini** [comment]
I have a very active need to support this layer on rocko so would be happy to maintain that branch.  I can also help with sumo.

**Comment by jiazhang0** [comment]
Sounds great. I will start the work and we will have rocko and sumo branches for LTS.

**Pull request merged**
