### PR TITLE
2 issues fix

### PR DESCRIPTION
**Pull request by yizhao1**

### CODE REVIEW

**Comment by trini** [comment]
Please revert 7a6e256 as we intentionally copy and not move the file as we need both files to exist in order to have a valid stable binary for the file to exist and have secure boot functional wic images be created.

**Comment by yizhao1** [comment]
Hi Tom, I'm confused about your reply. I use "copy" not "move" because "move" would cause a do_deploy failure.

**Comment by trini** [comment]
Ah, right, sorry, I mis-spoke since I mis-recalled the details.  But can you describe the problem you were seeing exactly?  I had to make some changes around here in order to make generating wic images just work which is why it moves the file and then makes a symlink in the next step.  You're reverting it back to a copy and then still leaving the symlink.  Are you seeing something broken under the deploy directory?

**Comment by yizhao1** [comment]
Please refer line 88 in linux-yocto-efi-secure-boot.inc:
        if [ -f "${B}/${KERNEL_OUTPUT_DIR}/$type.p7b" ]; then
            base_name="${type}-${KERNEL_IMAGE_BASE_NAME}.bin.p7b"

            install -m 0644 "${B}/${KERNEL_OUTPUT_DIR}/$type.p7b" "${DEPLOYDIR}/$base_name"
            ln -sf "$base_name" "${DEPLOYDIR}/$type-${KERNEL_IMAGE_SYMLINK_NAME}.bin.p7b"
            ln -sf "$base_name" "${DEPLOYDIR}/$type.p7b"
        fi

It tries to copy p7b file from KERNEL_OUTPUT_DIR to DEPLOYDIR. but in your commit, the p7b is already *moved* from the KERNEL_OUTPUT_DIR. There is no p7b file and these codes do nothing. That means the p7b file is not installed in deploy directory. When generate an image, it tries to found p7b file in deploy/image/intel-x86-64 directory, but the file is not in there that causes an error.

**Pull request merged**
